import plugin from "tailwindcss/plugin";
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@dxp-feed/ui/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    screens: {
      xxss: "320px",
      "4xs": "360px",
      "3xs": "375px",
      "2xs": "414px",
      xs: "480px",
      sm: "576px",
      md: "768px",
      "2md": "834px",
      lgs: "991px",
      lg: "1024px",
      "2lg": "1200px",
      xl: "1280px",
      "2xl": "1366px",
      "3xl": "1400px",
      "4xl": "1440px",
      "5xl": "1536px",
      "6xl": "1600px",
      "7xl": "1680px",
      "8xl": "1920px",
    },
    extend: {
      backgroundSize: {
        "25px": "25px",
      },
      fontSize: {
        xs: ["0.625rem", "1.125rem"],
        sm: ["0.75rem", "1.125rem"],
        body: ["0.875rem", "1.3125rem"],
        base: ["1rem", "1.5rem"],
        md: ["1.125rem", "1.688rem"],
        xl: ["1.25rem", "1.875rem"],
        "2xl": ["1.5rem", "2.25rem"],
        "3xl": ["1.75rem", "2.625rem"],
        "4xl": ["2.25rem", "3.375rem"],
        "5xl": ["2.5rem", "3.75rem"],
        "6xl": ["3rem", "4.5rem"],
      },
      colors: {
        // your entire color section remains unchanged
        brandSecondary: "var(--brandSecondary)",
        brandPrimary: "var(--brandPrimary)",
        brandBlack: "var(--brandBlack)",
        brandWhite: "var(--brandWhite)",
        brandError: "var(--brandError)",
        primary100: "var(--primary100)",
        primary200: "var(--primary200)",
        primary300: "var(--primary300)",
        primary400: "var(--primary400)",
        primary500: "var(--primary500)",
        primary600: "var(--primary600)",
        primaryTag: "var(--primaryTag)",
        grey50: "var(--grey50)",
        grey100: "var(--grey100)",
        grey150: "var(--grey150)",
        grey200: "var(--grey200)",
        grey250: "var(--grey250)",
        grey300: "var(--grey300)",
        grey350: "var(--grey350)",
        grey400: "var(--grey400)",
        grey450: "var(--grey450)",
        grey500: "var(--grey500)",
        grey550: "var(--grey550)",
        grey600: "var(--grey600)",
        grey700: "var(--grey700)",
        grey750: "var(--grey750)",
        grey800: "var(--grey800)",
        grey900: "var(--grey900)",
        grey950: "var(--grey950)",
        red100: "var(--red100)",
        red200: "var(--red200)",
        red300: "var(--red300)",
        gray100: "var(--gray100)",
        black100: "var(--black100)",
        black200: "var(--black200)",
        green100: "var(--green100)",
        green200: "var(--green200)",
        green300: "var(--green300)",
        greenLight: "var(--greenLight)",
        lighterGrey: "var(--lighterGrey)",
        lightBlue: "var(--lightBlue)",
        yellow: "var(--yellow)",
        yellow100: "var(--yellow100)",
        overlay: "var(--bg-overlay)",
        lightpurple: "var(--lightpurple)",
        lightpurple300: "var(--lightpurple300)",
        purpleDark: "var(--purpleDark)",
        purple100: "var(--purple100)",
        purple200: "var(--purple200)",
        purple300: "var(--purple300)",
        orange50: "var(--orange50)",
        orange150: "var(--orange150)",
        orange250: "var(--orange250)",
        yellow50: "var(--yellow50)",
        yellow150: "var(--yellow150)",
        hovercolor: "var(--hovercolor)",
        orange100: "var(--orange100)",
        orange200: "var(--orange200)",
        lightgray: "var(--lightgray)",
        blue100: "var(--blue100)",
        brown100: "var(--brown100)",
        darkgreen: "var(--darkgreen)",
      },
      backgroundImage: {
        blackgradientright: "var(--blackgradientright)",
        blackgradientleft: "var(--blackgradientleft)",
        "arrow-down": "url('/subscription/icon-arrow-down.svg')",
        "loader-icon": "url('/loader.svg')",
        "circle-tick": "url('/circle-tick.svg')",
      },
      boxShadow: {
        cardShadow: "var(--cardShadow)",
        modalshadow: "var(--modalshadow)",
        GlowOfferShadow: "var(--GlowOfferShadow)",
        navshadow: "var(--navshadow)",
        red: "var(--red)",
        purple: "var(--purple)",
        customShadow: "var(--custom-shadow)",
      },
      fontFamily: {
        primaryFont: ["var(--poppins)"],
        sans: ["var(--font-secondary)"],
        neo: ["var(--font-neodisplay)"],
      },
      dropShadow: {
        custom: "var(--custom)",
      },
      opacity: {
        0: "0",
        25: "0.25",
        50: "0.5",
        75: "0.75",
        100: "1",
      },
      keyframes: {
        slideDown: {
          "0%": { transform: "translateY(0)", opacity: "1" },
          "100%": { transform: "translateY(100%)", opacity: "0" },
        },
        slideUp: {
          "0%": { transform: "translateY(-100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        smoothScroll: {
          "0%": { transform: "translateY(-60%)" },
          "100%": { transform: "translateY(0)" },
        },
      },
      animation: {
        "slide-down": "slideDown 0.5s ease-in-out forwards",
        "slide-up": "slideUp 0.5s ease-in-out forwards",
        smoothScroll: "smoothScroll 0.6s ease-in-out forwards",
      },
    },
  },
  plugins: [
    plugin(function ({ addComponents }) {
      addComponents({
        ".range-thumb-white": {
          "&::-webkit-slider-thumb": {
            appearance: "none",
            height: "26px",
            width: "26px",
            borderRadius: "9999px",
            backgroundColor: "#ffffff",
            border: "4px solid #00A651",
            marginTop: "-8px",
            cursor: "pointer",
          },
          "&::-moz-range-thumb": {
            height: "26px",
            width: "26px",
            borderRadius: "9999px",
            backgroundColor: "#ffffff",
            border: "4px solid #00A651",
            cursor: "pointer",
          },
        },
      });
    }),
  ],
};

export default config;
