resource_group_name      = "nextapp-rg"
location                 = "Central US"
acr_name                 = "nextappacr"
app_service_plan_name    = "nextapp-plan"
app_service_name         = "nextapp-webapp"
