resource_group_name     = "nextapp-rg"
location                = "Central US"
app_service_plan_name   = "nextapp-plan"
web_app_name            = "nextapp-web"
acr_name                = "nextappacr"
docker_image_name       = "next-app"
docker_image_tag        = "latest"
