// app/layout.tsx
import type { Metadata } from "next";
import "@/styles/globals.css";
export const metadata: Metadata = {
  title: "Modules Gallery",
  description: "Generated by Tru Agency",
};

export default function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {/* <Header /> */}
      <div className="flex min-h-screen">
        {/* <Sidebar /> */}
        <div className="flex flex-col flex-1">
          <main className="flex-1 p-4">{children}</main>
          {/* <Footer /> */}
        </div>
      </div>
    </div>
  );
}
