// app/layout.tsx
import type { Metadata } from "next";
import "@/styles/globals.css";
import Sidebar from "@/templates/reactSidebar/reactSidebar";
import Header from "@/templates/header/Index";
import Footer from "@/templates/footer/Index";
import { poppins } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Modules Gallery",
  description: "Generated by Tru Agency",
};

export default function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Header />
        <div className="flex min-h-screen">
          <Sidebar />
          <div className="flex flex-col flex-1">
            <main className="flex-1 p-4">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
