name: Terraform Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push-docker:
    name: Build & Push Docker to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name nextappacr

      - name: Build Docker Image
        run: |
          docker build -t next-app:latest .
          docker tag next-app:latest nextappacr.azurecr.io/next-app:latest

      - name: Push Docker Image to ACR
        run: docker push nextappacr.azurecr.io/next-app:latest

  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: build-and-push-docker

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Debug Azure Env Vars
        run: |
          echo "SUBSCRIPTION: $ARM_SUBSCRIPTION_ID"
          echo "CLIENT: $ARM_CLIENT_ID"
          echo "TENANT: $ARM_TENANT_ID"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_SP_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_SP_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_SP_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_ACR_NAME: nextappacr
          TF_VAR_IMAGE_NAME: next-app

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_SP_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_SP_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_SP_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_ACR_NAME: nextappacr
          TF_VAR_IMAGE_NAME: next-app
