name: Terraform + Next.js Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    outputs:
      acr_login_server: ${{ steps.acr.outputs.acr_login_server }}
      acr_name: ${{ steps.acr.outputs.acr_name }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var-file=dev.tfvars -out=tfplan
        env:
          TF_VAR_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_SP_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_SP_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_SP_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_ACR_NAME: nextappacr
          TF_VAR_IMAGE_NAME: next-app

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_SP_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_SP_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_SP_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_ACR_NAME: nextappacr
          TF_VAR_IMAGE_NAME: next-app

      - name: Output ACR Info
        id: acr
        working-directory: terraform
        run: |
          echo "acr_login_server=$(terraform output -raw acr_login_server)" >> $GITHUB_OUTPUT
          echo "acr_name=$(terraform output -raw acr_name)" >> $GITHUB_OUTPUT

  build-and-push-docker:
    name: Build & Push Docker to ACR
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ needs.terraform.outputs.acr_name }}

      - name: Build Docker Image with cache
        working-directory: module-gallery-react-stage
        run: |
          IMAGE_TAG=${GITHUB_REF_NAME}-latest
          docker build --cache-from ${{ needs.terraform.outputs.acr_login_server }}/next-app:latest -t next-app:$IMAGE_TAG .
          docker tag next-app:$IMAGE_TAG ${{ needs.terraform.outputs.acr_login_server }}/next-app:$IMAGE_TAG

      - name: Push Docker Image to ACR
        run: |
          IMAGE_TAG=${GITHUB_REF_NAME}-latest
          docker push ${{ needs.terraform.outputs.acr_login_server }}/next-app:$IMAGE_TAG

  deploy-to-webapp:
    name: Deploy Docker Image to Azure Web App
    runs-on: ubuntu-latest
    needs: build-and-push-docker

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Docker Image to Azure Web App
        run: |
          # Use proper branch name for image tag (strip refs/heads/)
          IMAGE_TAG=${GITHUB_REF_NAME##*/}-latest

          # Get ACR info from previous job outputs
          ACR_NAME=${{ needs.build-and-push-docker.outputs.acr_name }}
          ACR_LOGIN_SERVER=${{ needs.build-and-push-docker.outputs.acr_login_server }}

          # Validate ACR_NAME
          if [ -z "$ACR_NAME" ]; then
            echo "Error: ACR_NAME is empty!"
            exit 1
          fi

          # Get ACR credentials (if not using Managed Identity)
          ACR_USERNAME=$(az acr credential show -n $ACR_NAME --query "username" -o tsv)
          ACR_PASSWORD=$(az acr credential show -n $ACR_NAME --query "passwords[0].value" -o tsv)

          # Deploy container to Azure Web App
          az webapp config container set \
            --name nextapp-web \
            --resource-group nextapp-rg \
            --container-image-name $ACR_LOGIN_SERVER/next-app:$IMAGE_TAG \
            --registry-login-server $ACR_LOGIN_SERVER \
            --registry-username $ACR_USERNAME \
            --registry-password $ACR_PASSWORD

          # Set environment variables
          az webapp config appsettings set \
            --name nextapp-web \
            --resource-group nextapp-rg \
            --settings NODE_ENV=production WEBSITES_PORT=3000 WEBSITES_ENABLE_APP_SERVICE_STORAGE=true

          # Restart Web App
          az webapp restart \
            --name nextapp-web \
            --resource-group nextapp-rg

      - name: Verify deployment
        run: |
          echo "Deployment finished. Web App status:"
          az webapp show --name nextapp-web --resource-group nextapp-rg --query state
